remote_theme: PfeifferChPT/indigo-linkinbio
name: "Pfeiffer GPS Portal - CDN" 
bio: "Hosts files that Traccar web app depends on."

# twitter summary info
description: Hosts files that Traccar web app depends on..

# if it's an external image, update below for true
# better with square images
external-image: false
picture: pwa-512x512.png

url: https://gps.pfeiffer.world
permalink: /:title/
github: PfeifferCh
